import type { RenderContext } from './context.js';
import { formatDuration, runTotals, shortCommit, statusWord } from './context.js';
import { describeGap } from '../evaluate.js';

function esc(text: string): string {
  return text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

const STATUS_COLOR: Record<string, string> = {
  PASS: '#1a7f37',
  FAIL: '#cf222e',
  GAP: '#9a6700',
};

function badge(status: string): string {
  const color = STATUS_COLOR[status] ?? '#57606a';
  return `<span class="badge" style="background:${color}">${esc(status)}</span>`;
}

export function renderIndexHtml(ctx: RenderContext): string {
  const totals = runTotals(ctx.run);
  const { results, gaps } = ctx.evaluation;

  const metaRows: string[] = [
    `<tr><th>Started (UTC)</th><td>${esc(ctx.run.startTime)}</td></tr>`,
    `<tr><th>Duration</th><td>${esc(formatDuration(ctx.run.durationMs))}</td></tr>`,
  ];
  if (ctx.run.playwrightVersion) {
    metaRows.push(`<tr><th>Playwright</th><td>${esc(ctx.run.playwrightVersion)}</td></tr>`);
  }
  if (ctx.git) {
    metaRows.push(`<tr><th>Commit</th><td><code>${esc(shortCommit(ctx.git.commit))}</code></td></tr>`);
    if (ctx.git.branch) metaRows.push(`<tr><th>Branch</th><td><code>${esc(ctx.git.branch)}</code></td></tr>`);
    if (ctx.git.tag) metaRows.push(`<tr><th>Tag</th><td><code>${esc(ctx.git.tag)}</code></td></tr>`);
    if (ctx.git.dirty !== undefined) {
      metaRows.push(`<tr><th>Working tree</th><td>${ctx.git.dirty ? '<strong>dirty</strong>' : 'clean'}</td></tr>`);
    }
  } else {
    metaRows.push('<tr><th>Git</th><td>(no repository metadata recorded)</td></tr>');
  }
  metaRows.push(
    `<tr><th>Tests</th><td>${totals.total} total — ${totals.passed} passed, ${totals.failed} failed, ${totals.skipped} skipped, ${totals.flaky} flaky</td></tr>`,
  );
  for (const key of Object.keys(ctx.doc.meta)) {
    metaRows.push(`<tr><th>${esc(key)}</th><td>${esc(ctx.doc.meta[key] ?? '')}</td></tr>`);
  }

  const controlRows = results
    .map((r) => {
      const passing = r.passed + r.flaky;
      const evidence =
        r.tests.length === 0
          ? 'no matching tests'
          : `${passing}/${r.tests.length} passing (min ${r.control.evidence.minTests})`;
      const styles =
        r.stylesExercised.length === 0 ? '—' : r.stylesExercised.map((s) => esc(s.style)).join(', ');
      return `<tr>
  <td><a href="controls/${esc(r.control.id)}.md">${esc(r.control.id)}</a></td>
  <td>${esc(r.control.title)}</td>
  <td>${badge(statusWord(r.status))}</td>
  <td>${esc(evidence)}</td>
  <td>${styles}</td>
</tr>`;
    })
    .join('\n');

  const gapItems =
    gaps.length === 0
      ? '<p>No coverage gaps detected in this run.</p>'
      : `<ul>${gaps.map((g) => `<li>${esc(describeGap(g))}</li>`).join('')}</ul>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Evidence pack ${esc(ctx.packId)}</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         margin: 2rem auto; max-width: 60rem; padding: 0 1rem; color: #1f2328; }
  h1 { font-size: 1.4rem; } h2 { font-size: 1.1rem; margin-top: 2rem; }
  code { background: #f6f8fa; padding: 0.1em 0.35em; border-radius: 4px; font-size: 0.9em; }
  table { border-collapse: collapse; width: 100%; margin: 0.75rem 0; }
  th, td { border: 1px solid #d0d7de; padding: 0.4rem 0.6rem; text-align: left;
           vertical-align: top; font-size: 0.9rem; }
  th { background: #f6f8fa; }
  .badge { color: #fff; border-radius: 999px; padding: 0.1em 0.7em; font-size: 0.78rem;
           font-weight: 600; letter-spacing: 0.03em; }
  .note { color: #57606a; font-size: 0.85rem; }
</style>
</head>
<body>
<h1>Evidence pack <code>${esc(ctx.packId)}</code></h1>
<p class="note">Generated by test-evidence-packs v${esc(ctx.generatorVersion)}.
Integrity: <code>manifest.json</code> records the sha256 of every file in this pack;
the pack's ledger entry chains it to prior runs. Verify with <code>tep verify</code>.</p>

<h2>Run</h2>
<table>${metaRows.join('\n')}</table>

<h2>Controls</h2>
<table>
<tr><th>Control</th><th>Title</th><th>Status</th><th>Passing evidence</th><th>Styles exercised</th></tr>
${controlRows}
</table>

<h2>Coverage gaps</h2>
${gapItems}

<h2>Files</h2>
<ul>
  <li><a href="EVIDENCE.md">EVIDENCE.md</a> — human-readable summary</li>
  <li><a href="GAPS.md">GAPS.md</a> — coverage gaps in detail</li>
  <li><a href="manifest.json">manifest.json</a> — machine-readable manifest with file hashes</li>
  <li><code>controls/</code> — one evidence document per control</li>
  <li><code>inputs/</code> — verbatim copies of the controls map and test report</li>
</ul>
</body>
</html>
`;
}
