import { describeGap } from '../evaluate.js';
import type { ControlResult, Gap } from '../types.js';
import type { RenderContext } from './context.js';
import { formatDuration, outcomeWord, runTotals, shortCommit, statusWord } from './context.js';

/** Escape a string for use inside a Markdown table cell. */
function cell(text: string): string {
  return text.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function gitRows(ctx: RenderContext): string[] {
  if (!ctx.git) return ['| Git | (no repository metadata recorded) |'];
  const rows = [`| Commit | \`${ctx.git.commit}\` |`];
  if (ctx.git.branch) rows.push(`| Branch | \`${cell(ctx.git.branch)}\` |`);
  if (ctx.git.tag) rows.push(`| Tag | \`${cell(ctx.git.tag)}\` |`);
  if (ctx.git.dirty !== undefined) {
    rows.push(`| Working tree | ${ctx.git.dirty ? '**dirty** (uncommitted changes at run time)' : 'clean'} |`);
  }
  return rows;
}

function runSection(ctx: RenderContext): string[] {
  const totals = runTotals(ctx.run);
  const lines = [
    '## Run',
    '',
    '| Field | Value |',
    '| --- | --- |',
    `| Started (UTC) | ${ctx.run.startTime} |`,
    `| Duration | ${formatDuration(ctx.run.durationMs)} |`,
  ];
  if (ctx.run.playwrightVersion) lines.push(`| Playwright | ${cell(ctx.run.playwrightVersion)} |`);
  lines.push(...gitRows(ctx));
  lines.push(
    `| Tests | ${totals.total} total — ${totals.passed} passed, ${totals.failed} failed, ${totals.skipped} skipped, ${totals.flaky} flaky |`,
  );
  for (const key of Object.keys(ctx.doc.meta)) {
    lines.push(`| ${cell(key)} | ${cell(ctx.doc.meta[key] ?? '')} |`);
  }
  return lines;
}

export function renderEvidenceMd(ctx: RenderContext): string {
  const { results, gaps } = ctx.evaluation;
  const lines: string[] = [
    `# Evidence pack \`${ctx.packId}\``,
    '',
    `Generated by test-evidence-packs v${ctx.generatorVersion} from a Playwright test run.`,
    'This pack maps declared controls to the tests that exercised them in this run.',
    '',
    '**Integrity:** `manifest.json` records the sha256 of every file in this pack, and the',
    "pack's entry in `../../ledger.jsonl` chains it to all prior runs. Run",
    '`tep verify <evidence-dir>` to check both.',
    '',
    ...runSection(ctx),
    '',
    '## Controls',
    '',
    '| Control | Title | Status | Passing evidence | Styles exercised |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const r of results) {
    const passing = r.passed + r.flaky;
    const evidence =
      r.tests.length === 0
        ? 'no matching tests'
        : `${passing}/${r.tests.length} passing (min ${r.control.evidence.minTests})`;
    const styles = r.stylesExercised.length === 0 ? '—' : r.stylesExercised.map((s) => s.style).join(', ');
    lines.push(
      `| [${cell(r.control.id)}](controls/${r.control.id}.md) | ${cell(r.control.title)} | ${statusWord(r.status)} | ${evidence} | ${styles} |`,
    );
  }
  const passedCount = results.filter((r) => r.status === 'passed').length;
  lines.push('');
  lines.push(
    `**${passedCount} of ${results.length} control(s) fully evidenced.** ` +
      (gaps.length === 0
        ? 'No coverage gaps detected.'
        : `${gaps.length} coverage gap(s) detected — see [GAPS.md](GAPS.md).`),
  );
  lines.push('');
  return lines.join('\n');
}

export function renderControlMd(ctx: RenderContext, result: ControlResult): string {
  const c = result.control;
  const lines: string[] = [`# ${c.id} — ${c.title}`, ''];
  if (c.description) {
    lines.push(...c.description.trim().split('\n').map((l) => `> ${l}`), '');
  }
  lines.push(`- **Status:** ${statusWord(result.status)}`);
  if (c.owner) lines.push(`- **Owner:** ${c.owner}`);
  if (c.references.length > 0) lines.push(`- **References:** ${c.references.join(' · ')}`);
  lines.push(`- **Pack:** \`${ctx.packId}\``);
  if (ctx.git) {
    const bits = [`commit \`${shortCommit(ctx.git.commit)}\``];
    if (ctx.git.branch) bits.push(`branch \`${ctx.git.branch}\``);
    if (ctx.git.tag) bits.push(`tag \`${ctx.git.tag}\``);
    lines.push(`- **Version under test:** ${bits.join(' · ')}`);
  }
  lines.push(`- **Run started (UTC):** ${ctx.run.startTime}`);
  lines.push('');

  lines.push('## Evidence requirements', '');
  lines.push('| Requirement | Expected | Observed | Met |');
  lines.push('| --- | --- | --- | --- |');
  const passing = result.passed + result.flaky;
  lines.push(
    `| Passing tests | ≥ ${c.evidence.minTests} | ${passing} | ${passing >= c.evidence.minTests && passing > 0 ? 'yes' : 'NO'} |`,
  );
  for (const style of c.evidence.styles) {
    const ev = result.stylesExercised.find((s) => s.style === style);
    const observed = ev
      ? `${ev.testIds.length} passing test(s)${ev.cases.length > 0 ? ` — cases: ${ev.cases.map(cell).join(', ')}` : ''}`
      : 'not exercised';
    lines.push(`| Style: ${style} | exercised by a passing test | ${observed} | ${ev ? 'yes' : 'NO'} |`);
  }
  lines.push('');

  lines.push('## Tests', '');
  if (result.tests.length === 0) {
    lines.push('No tests in this run matched this control.', '');
  } else {
    lines.push('| Test | Location | Project | Outcome | Duration | Retries |');
    lines.push('| --- | --- | --- | --- | --- | --- |');
    for (const t of result.tests) {
      lines.push(
        `| ${cell(t.title)} | \`${cell(`${t.file}:${t.line}`)}\` | ${cell(t.projectName || '—')} | ${outcomeWord(t.outcome)} | ${formatDuration(t.durationMs)} | ${t.retries} |`,
      );
    }
    lines.push('');
  }

  const failures = result.tests.filter((t) => t.errors.length > 0);
  if (failures.length > 0) {
    lines.push('## Failures', '');
    for (const t of failures) {
      lines.push(`- **${cell(t.title)}** (\`${t.file}:${t.line}\`)`);
      for (const e of t.errors) lines.push(`  - ${cell(e)}`);
    }
    lines.push('');
  }

  const withAttachments = result.tests.filter((t) => t.attachments.length > 0);
  if (withAttachments.length > 0) {
    lines.push('## Artifacts', '');
    for (const t of withAttachments) {
      for (const a of t.attachments) {
        const hash = a.sha256 ? ` — sha256 \`${a.sha256}\`` : '';
        const loc = a.path ? ` at \`${cell(a.path)}\`` : ' (inline)';
        lines.push(`- ${cell(t.title)}: **${cell(a.name)}** (${cell(a.contentType)})${loc}${hash}`);
      }
    }
    lines.push(
      '',
      '> Artifact files are referenced and hashed, not copied into the pack. A recorded',
      '> sha256 makes later alteration of the artifact detectable.',
      '',
    );
  }

  return lines.join('\n');
}

function gapSection(title: string, gaps: Gap[], lines: string[]): void {
  if (gaps.length === 0) return;
  lines.push(`## ${title}`, '');
  for (const gap of gaps) {
    lines.push(`- ${describeGap(gap)}`);
    if (gap.kind === 'unknown-control-tag') {
      for (const t of gap.tests) lines.push(`  - ${cell(t)}`);
    }
  }
  lines.push('');
}

export function renderGapsMd(ctx: RenderContext): string {
  const { gaps } = ctx.evaluation;
  const lines: string[] = ['# Coverage gaps', ''];
  if (gaps.length === 0) {
    lines.push('No coverage gaps detected in this run.', '');
    return lines.join('\n');
  }
  lines.push(
    `${gaps.length} gap(s) detected. A gap means a declared control lacks the evidence it`,
    'requires in this run — it does not by itself mean the underlying control failed.',
    '',
  );
  gapSection(
    'Controls with no passing evidence',
    gaps.filter((g) => g.kind === 'no-passing-evidence'),
    lines,
  );
  gapSection(
    'Controls below their minimum test count',
    gaps.filter((g) => g.kind === 'insufficient-tests'),
    lines,
  );
  gapSection(
    'Declared styles not exercised',
    gaps.filter((g) => g.kind === 'missing-style'),
    lines,
  );
  gapSection(
    'Control tags that match no declared control',
    gaps.filter((g) => g.kind === 'unknown-control-tag'),
    lines,
  );
  return lines.join('\n');
}
